version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet_care_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-care-backend
    ports:
      - "9192:9192"
    env_file:
      - .env
    depends_on:
      - mysql
      - rabbitmq
      - redis
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
